import type { ToolGuide } from './types'

export const toolGuides: Record<string, ToolGuide> = {
  'add-subtitle': {
    slug: 'add-subtitle',
    overview: 'Add Subtitle burns an existing .srt, .vtt, or .ass file into a video on the Kits server. It does not generate subtitles or invent timing for plain text.',
    steps: [
      'Open Add Subtitle.',
      'Upload one video (MP4, WebM, MOV, or MKV) and one subtitle file.',
      'Choose burn-in or mux, then set font size, color, outline, position, and bottom margin for burn-in.',
      'Process the video. Progress uses processed time over duration when FFmpeg reports it.',
      'Preview the result. It downloads automatically once. Use Download again for another copy.',
    ],
    optionDocs: [
      { name: 'Mode', description: 'Burn in draws captions into the picture. Mux attaches a subtitle track without burning.' },
      { name: 'Font size / Text color', description: 'Burn-in only. Applied through FFmpeg subtitle styling, not a custom filter string.' },
      { name: 'Background / outline', description: 'None, outline, or a solid caption box.' },
      { name: 'Position / Bottom margin', description: 'Bottom, middle, or top, plus vertical margin in pixels.' },
    ],
    output: 'A video with burned-in or muxed subtitles, preview, duration, size, resolution, and an automatic download.',
    example: 'An MP4 clip plus an .srt file can be burned in with white 24px captions at the bottom.',
    troubleshooting: [
      { problem: 'The subtitle file is rejected', solution: 'Use .srt, .vtt, or .ass with real cue times. Plain text without timestamps is not supported.' },
      { problem: 'The video has no picture', solution: 'The source must include a video stream. Audio-only files cannot be subtitled here.' },
    ],
    keywords: ['subtitle', 'caption', 'srt', 'vtt', 'ass', 'burn'],
  },
  'compress-image': {
    slug: 'compress-image',
    overview: 'Compress Image reduces JPEG, PNG, WebP, or AVIF file size in this browser. PNG uses Lossless, Balanced (default), or Strong modes instead of a quality slider.',
    steps: [
      'Open Compress Image.',
      'Drop an image into the upload area or choose a file.',
      'For PNG, pick Lossless, Balanced, or Strong. For JPEG and WebP, set quality (default 80).',
      'Compress the image and compare original size, compressed size, saved bytes, and processing time.',
      'The result downloads automatically once. Use Download again if you need another copy.',
    ],
    optionDocs: [
      { name: 'Mode', description: 'PNG only. Lossless keeps pixels and optimizes encoding. Balanced (default) may reduce colors when it shrinks the file without obvious damage. Strong is more aggressive. Quantized PNG is visually high quality, not mathematically lossless.' },
      { name: 'Quality', description: 'Applies to JPEG and WebP. Hidden for PNG output.' },
    ],
    output: 'A compressed image with preview, original vs new size, saved bytes, saved percentage, processing time, and an automatic download named from the source file.',
    example: 'A large product photo PNG can often become much smaller in Balanced mode. Photographic PNGs may also show a WebP conversion recommendation. Exact savings are not guaranteed.',
    troubleshooting: [
      { problem: 'The image cannot be opened', solution: 'Confirm the file is not corrupted and is JPEG, PNG, WebP, or AVIF.' },
      { problem: 'The output is the same size as the original', solution: 'The file may already be optimized. Try Strong for PNG, a lower JPEG/WebP quality, or convert a photo to WebP.' },
    ],
    keywords: ['compress', 'optimize', 'shrink', 'quality', 'png', 'jpeg', 'webp'],
  },
  'resize-image': {
    slug: 'resize-image',
    overview: 'Resize Image changes width and height in pixels or percent. You can lock the original proportions.',
    steps: [
      'Open Resize Image.',
      'Add a JPEG, PNG, WebP, or AVIF file.',
      'Choose pixels or percent.',
      'Enter width and height. Keep aspect ratio locked unless you want to stretch the image.',
      'Resize and preview.',
      'Download the result.',
    ],
    optionDocs: [
      { name: 'Unit', description: 'Pixels for exact size, or percent of the original dimensions.' },
      { name: 'Width / Height', description: 'Target size. With lock on, changing one side updates the other.' },
      { name: 'Lock aspect ratio', description: 'Keeps the original proportions.' },
    ],
    output: 'A resized image with preview and download.',
    example: 'A 4000-pixel photo can be scaled to a web width such as 1200px while keeping the same shape.',
    troubleshooting: [
      { problem: 'The image looks stretched', solution: 'Turn lock aspect ratio on, or match the original width-to-height ratio.' },
      { problem: 'Processing fails on a huge file', solution: 'The workspace rejects images over 40 megapixels or 16,384px on a side.' },
    ],
    keywords: ['resize', 'scale', 'dimensions', 'aspect ratio'],
  },
  'crop-image': {
    slug: 'crop-image',
    overview: 'Crop Image keeps a rectangular region of a photo and discards the rest.',
    steps: [
      'Open Crop Image.',
      'Add an image.',
      'Set the crop origin (X, Y) and the crop width and height in pixels.',
      'Crop the image and check the preview.',
      'Download the cropped file.',
    ],
    optionDocs: [
      { name: 'X / Y', description: 'Top-left of the crop, in pixels from the original image.' },
      { name: 'Width / Height', description: 'Size of the kept region. The crop must stay inside the image.' },
    ],
    output: 'A cropped image with preview and download.',
    example: 'You can keep a product in the center of a photo and drop unused background.',
    troubleshooting: [
      { problem: 'Crop fails', solution: 'Make sure the rectangle sits fully inside the image. Out-of-bounds crops are rejected.' },
    ],
    keywords: ['crop', 'cut', 'trim photo'],
  },
  'image-converter': {
    slug: 'image-converter',
    overview: 'Image Converter changes a photo between JPEG, PNG, and WebP. Quality applies when the output is JPEG or WebP.',
    steps: [
      'Open Image Converter.',
      'Add a JPEG, PNG, WebP, or AVIF file.',
      'Choose the output format.',
      'Adjust quality if the format supports it.',
      'Convert and download.',
    ],
    optionDocs: [
      { name: 'Format', description: 'JPEG, PNG, or WebP.' },
      { name: 'Quality', description: 'Shown for JPEG and WebP. PNG does not use this slider.' },
    ],
    output: 'A converted image file you can preview and download.',
    example: 'A PNG with a large file size can be saved as JPEG or WebP for a smaller web image.',
    troubleshooting: [
      { problem: 'Transparency disappeared', solution: 'JPEG has no alpha. Use PNG or WebP if you need a transparent background.' },
    ],
    keywords: ['convert', 'jpeg', 'png', 'webp'],
  },
  'merge-pdf': {
    slug: 'merge-pdf',
    overview: 'Merge PDF combines multiple PDF files into one. This runs on the Kits processing server.',
    steps: [
      'Open Merge PDF.',
      'Drop two or more PDF files. Order in the list is the merge order.',
      'Leave the options JSON as {} unless you need extra settings.',
      'Process and wait for the job to finish.',
      'Download the merged PDF.',
    ],
    optionDocs: [
      { name: 'Advanced options (JSON)', description: 'Optional job options. Merge does not require extra fields for a basic combine.' },
    ],
    output: 'One PDF download after the job completes.',
    example: 'Several one-page invoices can be merged into a single packet for sharing.',
    troubleshooting: [
      { problem: 'Process stays disabled', solution: 'Add at least two PDFs. Merge is a multi-file tool.' },
      { problem: 'Upload is rejected', solution: 'Use application/pdf files, up to 100 MB each, and at most 20 files.' },
    ],
    keywords: ['merge', 'combine', 'pdf', 'join'],
  },
  'split-pdf': {
    slug: 'split-pdf',
    overview: 'Split PDF extracts selected pages from a PDF on the server. Pages are listed in the options JSON.',
    steps: [
      'Open Split PDF.',
      'Add one PDF.',
      'Set the pages array in Advanced options, for example {"pages":[1]}.',
      'Process the job.',
      'Download the result.',
    ],
    optionDocs: [
      { name: 'pages', description: 'JSON array of 1-based page numbers to keep, for example [1] or [1,2,5].' },
    ],
    output: 'A PDF containing only the requested pages.',
    example: 'You can keep the first page of a long scan and download it on its own.',
    troubleshooting: [
      { problem: 'The job fails', solution: 'Check that pages exist in the file and that the JSON is valid.' },
    ],
    keywords: ['split', 'extract pages', 'pdf'],
  },
  'compress-pdf': {
    slug: 'compress-pdf',
    overview: 'Compress PDF reduces PDF size on the Kits server. Upload a PDF, process, then download.',
    steps: [
      'Open Compress PDF.',
      'Add one PDF (up to 100 MB).',
      'Process the job.',
      'Download the compressed file when the job completes.',
    ],
    output: 'A processed PDF download. Size reduction depends on the source file.',
    example: 'A scanned PDF can often become smaller after server compression, but already-optimized files may change little.',
    troubleshooting: [
      { problem: 'The file is not accepted', solution: 'Use a PDF under 100 MB.' },
      { problem: 'Processing is unavailable', solution: 'The API must be running. This tool does not compress in the browser.' },
    ],
    keywords: ['compress pdf', 'shrink pdf', 'optimize pdf'],
  },
  'json-formatter': {
    slug: 'json-formatter',
    overview: 'JSON Formatter pretty-prints JSON in your browser. Nothing is uploaded.',
    steps: [
      'Open JSON Formatter.',
      'Paste JSON into the editor.',
      'Click JSON Formatter.',
      'Fix any syntax error shown under the editor.',
      'Copy the result or download result.json.',
    ],
    output: 'Formatted JSON text, with copy and .json download.',
    example: 'A single-line API payload can be expanded with indentation so you can read keys and values.',
    troubleshooting: [
      { problem: 'The JSON could not be processed', solution: 'The input is not valid JSON. Check quotes, commas, and brackets.' },
    ],
    keywords: ['json', 'pretty print', 'format', 'beautify'],
  },
  'json-diff': {
    slug: 'json-diff',
    overview: 'JSON Diff compares two JSON documents in your browser. Nothing is uploaded.',
    steps: [
      'Open JSON Diff.',
      'Paste JSON A and JSON B.',
      'Use Format Both to pretty-print valid JSON. Swap A/B if you mixed the sides.',
      'Read added, removed, changed, and unchanged paths such as user.name or items[2].price.',
      'Copy Diff for a text report. Clear resets both editors.',
    ],
    optionDocs: [
      { name: 'Ignore object key order', description: 'On by default. Object keys are matched by name. Turn off to treat key reordering as a change. Array order always matters.' },
    ],
    output: 'A path list with Added, Removed, ~ Changed, and Unchanged labels, plus a copyable text diff.',
    example: 'Two API payloads that differ on settings.theme and items[2].price show those paths as changed, with new keys marked Added.',
    troubleshooting: [
      { problem: 'No diff appears', solution: 'Both sides must be valid JSON. Syntax errors are shown under JSON A and JSON B.' },
      { problem: 'Key order looks like a change', solution: 'Leave Ignore object key order on. JSON objects are unordered unless you need insertion-order checks.' },
    ],
    keywords: ['json', 'diff', 'compare', 'added', 'removed'],
  },
  'color-contrast-checker': {
    slug: 'color-contrast-checker',
    overview: 'Color Contrast Checker measures WCAG 2 contrast for one foreground color on one background. Nothing is uploaded. A pass does not mean a website is accessible.',
    steps: [
      'Open Color Contrast Checker.',
      'Set the foreground (text) color with the picker or HEX/RGB.',
      'Set the background color the same way.',
      'Read the contrast ratio and AA/AAA Pass or Fail for normal and large text.',
      'Use Swap colors to flip the pair. Check the 16px, 24px, button, and link preview.',
    ],
    optionDocs: [
      { name: 'Foreground / Background', description: 'HEX (#fff or #ffffff) or RGB (rgb(17, 17, 17) or 17, 17, 17). Alpha in rgba() is ignored.' },
      { name: 'Large text', description: 'WCAG large text is 18pt (24px) regular or 14pt bold. The preview uses 24px regular.' },
    ],
    output: 'Contrast ratio to two decimals, AA and AAA results for normal and large text, and a live preview.',
    example: 'Black text on white is 21.00 : 1 and passes every text level. #777777 on white is about 4.48 : 1 and fails AA for normal text.',
    troubleshooting: [
      { problem: 'The ratio does not appear', solution: 'Both colors must be valid HEX or RGB. Channel values cannot exceed 255.' },
      { problem: 'AA passes but AAA fails', solution: 'That is expected below 7:1 for normal text or 4.5:1 for large text.' },
    ],
    keywords: ['contrast', 'wcag', 'aa', 'aaa', 'accessibility', 'color'],
  },
  'regex-tester': {
    slug: 'regex-tester',
    overview: 'Regex Tester runs JavaScript RegExp in this browser. Nothing is uploaded. Sample patterns are generic examples, not universal validation guarantees.',
    steps: [
      'Open Regex Tester.',
      'Enter a regular expression and optional flags g, i, m, s, u, y.',
      'Paste test text. Matches highlight live with count, full match, capture groups, and start index.',
      'Copy Regex for a /pattern/flags literal, or Clear both fields.',
    ],
    optionDocs: [
      { name: 'g', description: 'Global. Find every match, not only the first.' },
      { name: 'i', description: 'Ignore case.' },
      { name: 'm', description: 'Multiline. ^ and $ match line starts and ends.' },
      { name: 's', description: 'DotAll. . matches newline.' },
      { name: 'u', description: 'Unicode. Enables \\p{} and full code-point matching.' },
      { name: 'y', description: 'Sticky. Match only at lastIndex (start of the text here).' },
    ],
    output: 'Highlighted matches, match count, full match, capture groups, and index. Invalid patterns show Invalid regular expression.',
    example: 'The sample email pattern finds addresses in pasted text. It is a generic example, not a complete email validator.',
    troubleshooting: [
      { problem: 'Invalid regular expression', solution: 'The pattern is not valid JavaScript RegExp. Check unclosed groups, brackets, and unicode flags.' },
      { problem: 'Only one match appears', solution: 'Turn on the g flag to find every occurrence.' },
    ],
    keywords: ['regex', 'regexp', 'regular expression', 'match', 'javascript'],
  },
  'css-clamp-calculator': {
    slug: 'css-clamp-calculator',
    overview: 'CSS Clamp Calculator builds a fluid clamp() from min/max viewport widths and min/max values. Invalid inputs never produce CSS.',
    steps: [
      'Open CSS Clamp Calculator.',
      'Choose Font Size, Padding, Margin, Gap, or Custom.',
      'Set min and max viewport widths in pixels.',
      'Set min and max values in px or rem, and the root size if using rem.',
      'Copy the generated CSS.',
    ],
    optionDocs: [
      { name: 'Viewport', description: 'Min must be less than max. Widths are pixels because vw is relative to the viewport.' },
      { name: 'Values', description: 'Min and max size in px or rem. Inverted sizes stay valid; clamp() bounds are ordered.' },
      { name: 'Root font size', description: 'Pixels per 1rem. Default 16. Must be greater than 0.' },
    ],
    output: 'A CSS declaration such as font-size: clamp(16px, 1.4286vw + 11.4286px, 32px);',
    example: 'Viewport 320px to 1440px and font-size 16px to 32px yields font-size: clamp(16px, 1.4286vw + 11.4286px, 32px);',
    troubleshooting: [
      { problem: 'No CSS is generated', solution: 'Min viewport must be less than max viewport, numbers must be finite, and the property must be a CSS name.' },
      { problem: 'rem looks wrong', solution: 'Set Root font size to the html font-size you actually use.' },
    ],
    keywords: ['css clamp', 'clamp()', 'fluid type', 'responsive font', 'vw'],
  },
  'sitemap-generator': {
    slug: 'sitemap-generator',
    overview: 'Sitemap Generator builds a protocol-0.9 sitemap.xml from http(s) URLs in the browser. Invalid URLs are flagged and omitted. Submitting a sitemap does not guarantee indexing.',
    steps: [
      'Open Sitemap Generator.',
      'Paste URLs one per line, or add them with Add URL.',
      'Optionally set lastmod, changefreq, and priority per URL.',
      'Remove exact duplicates if needed.',
      'Copy the XML or download sitemap.xml.',
    ],
    optionDocs: [
      { name: 'URL', description: 'Must be http or https. Relative, javascript:, data:, and credentialed URLs are rejected.' },
      { name: 'lastmod', description: 'Optional. YYYY-MM-DD, with an optional time.' },
      { name: 'changefreq', description: 'Optional. always, hourly, daily, weekly, monthly, yearly, or never.' },
      { name: 'priority', description: 'Optional. A number from 0.0 to 1.0.' },
    ],
    output: 'A well-formed sitemap.xml with only valid, unique URLs. Copy or download.',
    example: 'https://example.com/ and https://example.com/about become two <url> entries in a urlset.',
    troubleshooting: [
      { problem: 'A URL is marked invalid', solution: 'Use a full http or https URL. Relative paths and other schemes are rejected.' },
      { problem: 'A URL is missing from the XML', solution: 'It is either invalid or an exact duplicate of an earlier row.' },
    ],
    keywords: ['sitemap', 'sitemap.xml', 'xml sitemap', 'seo', 'urlset'],
  },
  'open-graph-generator': {
    slug: 'open-graph-generator',
    overview: 'Open Graph Generator builds og: and twitter: meta tags in the browser and shows approximate social-style previews. Nothing is uploaded. The cards are not pixel-identical to Facebook or X.',
    steps: [
      'Open Open Graph Generator.',
      'Enter page title, description, URL, and site name.',
      'Add a public https image URL if you have a share image.',
      'Choose website or article, then summary or summary_large_image.',
      'Copy the generated tags into your document head.',
    ],
    optionDocs: [
      { name: 'Page Title', description: 'Used for og:title and twitter:title.' },
      { name: 'Description', description: 'Used for og:description and twitter:description.' },
      { name: 'URL', description: 'Must be http or https. Invalid values are omitted from the HTML and flagged.' },
      { name: 'Image URL', description: 'Must be a public http or https URL. Relative, data, and credentialed URLs are rejected.' },
      { name: 'Content Type', description: 'og:type, either website or article.' },
      { name: 'Twitter/X card', description: 'summary_large_image or summary. Changes the X-style preview layout.' },
    ],
    output: 'Escaped HTML meta tags plus approximate Open Graph and X card previews.',
    example: 'A product page with title, description, canonical URL, and a 1200×630 PNG can produce both og:image and twitter:image tags.',
    troubleshooting: [
      { problem: 'The image URL is invalid', solution: 'Use a full http or https URL. Relative paths and data URLs are rejected.' },
      { problem: 'The preview image is blank', solution: 'The URL must be publicly fetchable by the browser. Mixed-content http images on https pages may also fail.' },
    ],
    keywords: ['open graph', 'og tags', 'twitter card', 'social preview', 'seo'],
  },
  'qr-code-generator': {
    slug: 'qr-code-generator',
    overview: 'QR Code Generator builds a QR image from text in the browser. You can set colors, size, margin, and error correction, then download PNG or SVG.',
    steps: [
      'Open QR Code Generator.',
      'Enter the text to encode.',
      'Optionally change colors, size (128–2048), margin, and error correction.',
      'Generate the QR code.',
      'Download PNG or SVG, or copy the image if the browser allows it.',
    ],
    optionDocs: [
      { name: 'Text', description: 'Payload encoded in the QR.' },
      { name: 'Foreground / Background', description: 'Module and background colors.' },
      { name: 'Size', description: 'Pixel width of the PNG, from 128 to 2048.' },
      { name: 'Margin', description: 'Quiet zone around the code, 0–20.' },
      { name: 'Error correction', description: 'L, M, Q, or H. Higher levels survive more damage but hold less data.' },
    ],
    output: 'PNG and SVG downloads, plus optional clipboard copy.',
    example: 'A short URL can be turned into a PNG for a poster or an SVG for print.',
    troubleshooting: [
      { problem: 'Generate stays blocked', solution: 'Enter the required text field first.' },
      { problem: 'PNG copy fails', solution: 'Some browsers block image clipboard writes. Use Download PNG instead.' },
    ],
    keywords: ['qr', 'barcode', 'generate qr'],
  },
  'audio-converter': {
    slug: 'audio-converter',
    overview: 'Audio Converter transcodes audio on the server with FFmpeg. The file is uploaded, processed as a job, then downloaded.',
    steps: [
      'Open Audio Converter.',
      'Add an audio or video file in a listed format.',
      'Choose MP3, WAV, M4A, OGG, FLAC, or Opus. Set bitrate only for lossy formats.',
      'Optionally change sample rate and channels, then convert.',
      'Preview the result and download the converted file.',
    ],
    optionDocs: [
      { name: 'Output format', description: 'MP3, WAV, M4A/AAC, OGG Vorbis, FLAC, or Opus.' },
      { name: 'Bitrate', description: '64k–320k for lossy formats. Ignored for WAV and FLAC.' },
      { name: 'Sample rate', description: 'Keep the original, or resample to 22050, 44100, or 48000 Hz.' },
      { name: 'Channels', description: 'Keep the original, or force mono or stereo.' },
    ],
    output: 'A converted audio file from the job result, with source/output size and duration.',
    example: 'A recording can be converted for playback on a device that prefers another container.',
    troubleshooting: [
      { problem: 'Upload is rejected', solution: 'Stay within 100 MB and use a listed audio or video type.' },
      { problem: 'This audio file could not be read', solution: 'The file is corrupt or not a real audio/video stream.' },
      { problem: 'This file has no audio stream', solution: 'Use a file that actually contains audio.' },
      { problem: 'Processing is unavailable', solution: 'The API and job worker must be running. This is not a browser converter.' },
    ],
    keywords: ['audio', 'convert', 'ffmpeg', 'mp3', 'wav', 'flac', 'opus'],
  },
  'noise-reduction': {
    slug: 'noise-reduction',
    overview: 'Noise Reduction removes hiss, fan, room, and keyboard noise from speech recordings on the Kits server. Standard uses fast FFmpeg filtering. Smart uses local RNNoise for stronger voice-focused suppression.',
    steps: [
      'Open Noise Reduction.',
      'Add an audio file (MP3, WAV, M4A, OGG, WebM, FLAC, or AAC).',
      'Choose Standard for steady hiss, or Smart for speech with background noise.',
      'Set strength to Light, Medium, or Strong.',
      'Process the job, then compare Original and Result in the preview players.',
      'Download the cleaned audio.',
    ],
    optionDocs: [
      { name: 'Mode', description: 'Standard is fast FFmpeg filtering for steady hiss. Smart is stronger voice-focused suppression with a local RNNoise model. Nothing is sent to a paid API.' },
      { name: 'Strength', description: 'Light, Medium (default), or Strong. FFmpeg parameters stay hidden.' },
    ],
    output: 'A processed audio file with original and result players so you can compare immediately.',
    example: 'A voice memo with laptop fan noise can be cleaned in Smart Medium, then compared with the original before download.',
    troubleshooting: [
      { problem: 'The result still sounds noisy', solution: 'Switch to Smart and try Strong. Standard is meant for steady hiss, not room or keyboard noise.' },
      { problem: 'Speech sounds thin or metallic', solution: 'Use Light or Medium. Strong can over-suppress on some voices.' },
      { problem: 'Processing is unavailable', solution: 'The API and job worker must be running. Smart also needs the local RNNoise model file.' },
    ],
    keywords: ['noise', 'denoise', 'hiss', 'rnnoise', 'afftdn'],
  },
  'video-compressor': {
    slug: 'video-compressor',
    overview: 'Video Compressor re-encodes video on the server to reduce size. It needs a temporary upload and a processing job.',
    steps: [
      'Open Video Compressor.',
      'Add an MP4, WebM, or QuickTime file (up to 100 MB).',
      'Process the job.',
      'Download when status is complete.',
    ],
    output: 'A compressed video download from the job.',
    example: 'A large clip can be re-encoded for easier sharing. Savings depend on the source.',
    troubleshooting: [
      { problem: 'The file is too large', solution: 'The upload cap is 100 MB per file in this workspace.' },
      { problem: 'The job fails', solution: 'Confirm the file plays locally and that the API is available.' },
    ],
    keywords: ['video', 'compress', 'ffmpeg', 'mp4'],
  },
  'merge-png': {
    slug: 'merge-png',
    overview: 'Merge PNG combines multiple PNG images into one PNG in your browser. You can stack them vertically, place them in a row, or arrange them on a grid. Files are not uploaded to Kits.',
    steps: [
      'Open Merge PNG.',
      'Drop or choose at least two PNG files.',
      'Reorder the list so the images appear in the order you want.',
      'Choose Vertical, Horizontal, or Grid. Gap, padding, alignment, and background stay compact. Extra sizing lives under Advanced options.',
      'Merge PNG to build the combined image in this browser. Auto optimize output is off by default.',
      'Preview the result, then download the PNG. The file also downloads automatically once.',
    ],
    optionDocs: [
      { name: 'Layout', description: 'Vertical stacks images top to bottom. Horizontal places them left to right. Grid fills rows left to right with 2, 3, 4, or Auto columns.' },
      { name: 'Sizing', description: 'Original keeps native pixel size. Fit evenly scales every image into the largest source box without stretching. Fit to largest width or height and custom cell size are under Advanced options.' },
      { name: 'Alignment', description: 'Places each image inside its column, row, or grid cell. Vertical uses left/center/right. Horizontal uses top/center/bottom. Grid uses both, defaulting to center.' },
      { name: 'Gap / Padding', description: 'Gap is space between images. Padding is the outer margin around the whole canvas. Both range from 0 to 32px.' },
      { name: 'Background', description: 'Transparent leaves pixels unfilled (default). White, black, or a custom color fills the canvas first.' },
      { name: 'Auto optimize output', description: 'Off by default. Turn it on to optimize PNG encoding locally without changing format or dimensions. Auto / Lossless / Strong are under Advanced options. The download is never larger than the generated file.' },
    ],
    output: 'One PNG with preview, image count, dimensions, layout, generated size, optimized size, and saved percentage. Download stays on this page and auto-downloads once.',
    example: 'Two screenshots can be stacked vertically with an 8px gap and a transparent background, then downloaded as a single PNG.',
    troubleshooting: [
      { problem: 'Merge is disabled', solution: 'Add at least two PNG images. JPEG and other formats are rejected.' },
      { problem: 'The merged image is too large', solution: 'Remove images, use a tighter layout, or choose a smaller sizing mode. The workspace will not silently downscale.' },
      { problem: 'A file cannot be read', solution: 'Confirm the PNG is not corrupted, then add it again.' },
    ],
    keywords: ['merge', 'combine', 'stack', 'png', 'collage', 'stitch'],
  },
  'voice-recorder': {
    slug: 'voice-recorder',
    overview: 'Voice Recorder captures microphone audio in the browser with MediaRecorder. Nothing is uploaded.',
    steps: [
      'Open Voice Recorder.',
      'Click Start recording and allow the microphone if asked.',
      'Pause, resume, or stop.',
      'Preview the clip, then download it, or reset to record again.',
    ],
    optionDocs: [
      { name: 'Start / Pause / Resume / Stop / Reset', description: 'Recording controls. Permission is requested only when you start.' },
    ],
    output: 'A recording in the container the browser actually produced (often WebM or M4A), not MP3 unless the browser encodes MP3.',
    troubleshooting: [
      { problem: 'Permission was denied', solution: 'Allow microphone access for this site in the browser settings, then start again.' },
      { problem: 'No microphone was found', solution: 'Connect a mic and retry.' },
    ],
    keywords: ['record', 'microphone', 'audio', 'mediarecorder'],
  },
}
